# dataset
dataset path: 'dataset_small'
annotations path: 'annotations'
datasize: 500

# spectrogram
n_fft: 512
hop_length: 256
n_mels: 128

# training
train split: 0.5
learning rate: 0.0001
train epochs: 50
batch size: 16
penalty: 100
plot: True

# model hyper-parameters
embed_size: 128
encoder: [64, 16]
encoder_kernel_size: 3
ff_hidden_size: 128
attention_limit: 128
transformer_layer_count: 2

debug dataset size: 6